### ISSUE TITLE
How can I get the "sp1s_aa_2py.mat" data?

### ISSUE THREAD

**Issue by dldl3D** [EderSantana/DeepEEG#3]
Hi,

I download the BCI competition II dataset. there are sp1s_aa.mat and sp1s_aa_1000Hz.mat data except for the sp1s_aa_2py.mat. And the y_test is not includeed in the sp1s_aa.mat . I want to not how I can get the sp1s_aa_2py.mat dataset?

Thanks very much.

**Comment by EderSantana** [comment]
I'm sorry @YuetianLiu it has been about a year since the last time I touched this code. I don't have those files anymore and I can't remember how I modified them. But I believe that sp1s_aa_2py.mat is just sp1s_aa.mat converted and using the train/test slipts. Check out the paper for possible more information
